### ISSUE TITLE
Could not find any Vault economy dependency! 

### ISSUE THREAD

**Issue by Blueeyestar** [GentleGravel/BuyRegion#3]
spigot-Vers.CraftBukkit version git-Spigot-8043ebc-89c52b7 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)

in the newest 1.14.1 is the newest Vault inside. Also recognized by almost all plugins only buyregion seems to have some problems with it

[07:02:15] [Server thread/INFO]: [BuyRegion] Disabling BuyRegion v2.1.5
[07:02:15] [Server thread/ERROR]: [BuyRegion] An error occurred during shutdown.
java.lang.NullPointerException: null
	at com.region.buyregion.BuyRegion.onDisable(BuyRegion.java:104) [BuyRegion-2.1.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) [Spigot-latest.jar:git-Spigot-8043ebc-89c52b7]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:377) [Spigot-latest.jar:git-Spigot-8043ebc-89c52b7]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437) [Spigot-latest.jar:git-Spigot-8043ebc-89c52b7]
	at com.region.buyregion.BuyRegion.onEnable(BuyRegion.java:65) [BuyRegion-2.1.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) [Spigot-latest.jar:git-Spigot-8043ebc-89c52b7]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [Spigot-latest.jar:git-Spigot-8043ebc-89c52b7]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [Spigot-latest.jar:git-Spigot-8043ebc-89c52b7]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458) [Spigot-latest.jar:git-Spigot-8043ebc-89c52b7]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372) [Spigot-latest.jar:git-Spigot-8043ebc-89c52b7]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440) [Spigot-latest.jar:git-Spigot-8043ebc-89c52b7]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [Spigot-latest.jar:git-Spigot-8043ebc-89c52b7]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:761) [Spigot-latest.jar:git-Spigot-8043ebc-89c52b7]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by dsevillamartin** [comment]
I'm guessing your issue was solved by updating BuyRegion to v2.2.0 ? At least the error during shutdown would've been fixed then, not sure about the Vault economy.

**Comment by Blueeyestar** [comment]
Yeah, everything's fine now. The plugin is great :)

**Comment by dsevillamartin** [comment]
Thanks! Glad to hear it!
