### ISSUE TITLE
[RedProtect] Could not pass event PlayerInteractEvent to BuyRegion v2.2.1 org.bukkit.event.EventException: null

### ISSUE THREAD

**Issue by Blueeyestar** [GentleGravel/BuyRegion#8]
[19:11:07] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to BuyRegion v2.2.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-df0eb25-0309d17]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-df0eb25-0309d17]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[spigot.jar:git-Spigot-df0eb25-0309d17]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[spigot.jar:git-Spigot-df0eb25-0309d17]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:429) ~[spigot.jar:git-Spigot-df0eb25-0309d17]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:435) ~[spigot.jar:git-Spigot-df0eb25-0309d17]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1267) ~[spigot.jar:git-Spigot-df0eb25-0309d17]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[spigot.jar:git-Spigot-df0eb25-0309d17]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot.jar:git-Spigot-df0eb25-0309d17]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot.jar:git-Spigot-df0eb25-0309d17]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-df0eb25-0309d17]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot.jar:git-Spigot-df0eb25-0309d17]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-df0eb25-0309d17]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot.jar:git-Spigot-df0eb25-0309d17]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895) [spigot.jar:git-Spigot-df0eb25-0309d17]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [spigot.jar:git-Spigot-df0eb25-0309d17]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot.jar:git-Spigot-df0eb25-0309d17]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:872) [spigot.jar:git-Spigot-df0eb25-0309d17]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [spigot.jar:git-Spigot-df0eb25-0309d17]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.IncompatibleClassChangeError: Expected static method br.net.fabiozumbi12.RedProtect.Bukkit.helpers.RedProtectUtil.isUUIDs(Ljava/lang/String;)Z
	at com.region.buyregion.plugins.RedProtectHook$RedRegion.lambda$getOwners$0(RedProtectHook.java:75) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_201]
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556) ~[?:1.8.0_201]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_201]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_201]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_201]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_201]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_201]
	at com.region.buyregion.plugins.RedProtectHook$RedRegion.getOwners(RedProtectHook.java:75) ~[?:?]
	at com.region.buyregion.BuyRegion.onPunchSign(BuyRegion.java:436) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor638.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-df0eb25-0309d17]
	... 19 more

**Comment by FabioZumbi12** [comment]
Humm, looking for a fix ;)

**Comment by FabioZumbi12** [comment]
I tryed to create a PR but seems your github is not updated with the redprotect hooks. Here is the class fixed: https://github.com/FabioZumbi12/BuyRegion/commit/0ff7afcd14c3a6eeaa795ad1eb89ca9bc8ba1d5a#diff-a28be649fdf0f583726887f38190f43cR74

**Comment by dsevillamartin** [comment]
@FabioZumbi12 The issue when creating the PR seems to be because of the different git histories, as you merged upstream into your fork and then created more commits separate from this repo.

The filter/map logic you have there can be simplified, I assume, by moving the try/catch into the map, returning null if error, and filter `!= null`. No time right now, will look at it tomorrow.

Just to know, is there a reason why you are maintaining your fork ? That could maybe confuse some users as both have the same features... for PRs, by the way, you can create branches from the original fork and work from them.

**Comment by FabioZumbi12** [comment]
Yeah, i didnt updated my fork to your last updates. I will reset and make all be equal yours ;)

I just put the modified class for a quick fiz and i think your suggestion ti simplify its valid!!

Edit: The errors is causd because i've maded the class RedprotectUtil private, then you need just to remove the dependency of this class and mad your own check if the owner is uuid.

**Comment by Blueeyestar** [comment]
I wanted to ask if the problem could be solved?
